# Generated by Django 4.2.4 on 2023-08-05 12:28

import agenda.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=150, null=True, verbose_name='Sobrenome')),
                ('telefone', models.CharField(max_length=13, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='Email')),
                ('imagem', models.ImageField(default='user.png', height_field=200, upload_to=agenda.models.user_directory_path, verbose_name='Foto', width_field=300)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'ordering': ['user', 'nome'],
            },
        ),
    ]
