# Generated by Django 4.2.4 on 2023-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_contato_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(default='user.png', height_field='200', upload_to='photos/', verbose_name='Foto', width_field='300'),
        ),
    ]
