# Generated by Django 4.2.4 on 2023-08-05 12:43

import agenda.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_contato_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='imagem',
            field=models.ImageField(default='user.png', upload_to=agenda.models.user_directory_path, verbose_name='Foto'),
        ),
    ]
